format_version: 10
pipelines:
  Frame-Extractor:
    group: mb-latam02
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-0644f82:
        git: https://github.com/latam02/Frame-Extractor.git
        username: matiboni99@gmail.com
        shallow_clone: false
        auto_update: true
        branch: MB-Jenkins
        encrypted_password: AES:ufoWDph+ro3h1pM+pXw0Ug==:kd4QiZq4jVgZDMv5gS2luA==
    stages:
    - step1:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          unit:
            resources:
              - ubuntu
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - pip install -r CONVERT_SERVICE/requirements.txt --no-cache-dir
                command: bash
                run_if: passed
